version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
      # Mounts the current directory as the current installed version of the plugin
      - ./:/var/www/html/wp-content/plugins/authress
      # Mounts a temporary mount point to overwrite the current plugin installed in the docker container
      #- /tmp/wordpress:/var/www/html/wp-content/plugins/authress

    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      DEVELOPMENT_DEBUG: 1
volumes:
  db_data: {}
  wordpress_data: {}