on:
  push:
    branches:
    - main
    - master
    - 'release/**'
  pull_request:
    branches:
    - main
    - master
    - 'release/**'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.3
        extensions: mbstring, xml, ctype, iconv, intl
        coverage: xdebug

    - name: Install Composer dependencies
      run: composer install -d authress --no-progress --prefer-dist --optimize-autoloader -q
    - name: Tag package
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' && github.event_name == 'push'
      run: |
        git tag ${GITHUB_REF/refs\/heads\/release\//}.$GITHUB_RUN_NUMBER
        git push origin ${GITHUB_REF/refs\/heads\/release\//}.$GITHUB_RUN_NUMBER

